---
- name: import global variables
  include_vars:
    dir: "{{ inventory_dir }}/group_vars/"

- name: add/upgrade EPEL and IUS repositories
  package:
    state: latest
    name:
      - epel-release
      - https://centos7.iuscommunity.org/ius-release.rpm

- name: install base packages
  package:
    state: present
    name:
      - certbot
      - duply
      - git
      - htop
      - python36
      - python36-pip
      - yum-plugin-replace

- name: enable SELinux
  selinux:
    policy: targeted
    state: enforcing

- name: Create admin group
  group:
    name: admin

- name: Create user accounts and add users to groups
  user:
    name: "{{ item }}"
    shell: "/usr/bin/bash"
    groups: "admin"
  loop: "{{ authorized_users }}"

- name: Add users to the sudoers
  copy:
    dest: "/etc/sudoers.d/{{ item }}"
    content: "{{ item }}  ALL=(ALL)  NOPASSWD: ALL"
  loop: "{{ authorized_users }}"

- name: Add authorized keys
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', '/home/'+ item +'/.ssh/id_ed25519.pub') }}"
    state: present
  loop: "{{ authorized_users }}"
