---
- name: Import global variables
  include_vars:
    dir: "{{ inventory_dir }}/group_vars/"

- name: Create webserver directory
  file:
    path: "/var/audit"
    state: directory
    mode: "0755"
    group: "admin"
    owner: "admin"

- name: Pull script from repo to ansible
  git:
    repo: https://github.com/BonjeBongo/NSSA320.01_Security_Scripts.git
    dest: "/tmp/"

- name: run audit script
  script: /tmp/NSSA320.01_Security_Scrtipt/audit_script.sh

- name: Archive logs
  archive:
    path: /tmp/audit
    dest: /tmp/{{ ansible_eth0.ipv4.address }}.log.zip
    format: zip

# - name: Fetch zip
#   fetch:
#     src: /tmp/{{ ansible_eth0.ipv4.address }}.log.zip
