---
- name: add influxdb.repo to /etc/yum.repos.d/
  copy:
    src: influxdb.repo
    dest: /etc/yum.repos.d/influxdb.repo
    mode: 0644
    setype: system_conf_t
    seuser: system_u

- name: install influxdb
  package:
    state: present
    name: influxdb

- name: add firewalld rule for InfluxDB server
  firewalld:
    state: enabled
    port: 8086/tcp
    immediate: yes
    permanent: yes

- name: add influxdb.conf to /etc/influxdb/
  template:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
    mode: 0644
    setype: etc_t
    seuser: system_u
  notify:
    - restart influxdb

- name: create directory for TLS certs
  file:
    state: directory
    path: /usr/lib/influxdb/tls/
    mode: 0750
    owner: influxdb
    group: influxdb
    setype: cert_t
    seuser: system_u

- name: create directory for host-specific certs
  file:
    state: directory
    path: "/usr/lib/influxdb/tls/{{ db_fqdn }}/"
    mode: 0750
    owner: influxdb
    group: influxdb
    setype: cert_t
    seuser: system_u

- name: symbolic link LetsEncrypt certs to InfluxDB TLS certs directory
  # Note: This step requires LetsEncrypt certs to already exist.
  file:
    state: link
    src: "/etc/letsencrypt/live/{{ db_fqdn }}/{{ item }}"
    dest: "/usr/lib/influxdb/tls/{{ db_fqdn }}/{{ item }}"
    seuser: system_u
  loop:
    - fullchain.pem
    - privkey.pem

- name: start/enable influxdb service
  service:
    name: influxdb
    state: started
    enabled: yes
