---
- name: import global variables
  include_vars:
    dir: "{{ inventory_dir }}/group_vars/"

- name: Install Certbot's Nginx package
  yum:
    name: python2-certbot-nginx
    state: present

- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ item.servername }}/cert.pem
    register: letsencrypt_cert
  loop: "{{ apache_vhosts }}"

- name: Stop services to allow certbot to generate a cert.
  service:
    name: "{{ item }}"
    state: stopped
  loop: "{{ certbot_create_standalone_stop_services }}"

- name: Generate new certificate if one doesn't exist.
  shell: "certbot certonly --standalone --noninteractive --agree-tos --email {{ certbot_admin_email }} -d {{ item.item.servername}}"
  loop: "{{ letsencrypt_cert.results }}"
  when: item.stat.exists == False

- name: Start services after cert has been generated.
  service:
    name: "{{ item }}"
    state: started
  loop: "{{ certbot_create_standalone_stop_services }}"
