galaxy_info:
  role_name: influxdb
  author: Justin W. Flory
  description: Deploy InfluxDB server on CentOS/RHEL systems

  license: MPLv2

  min_ansible_version: 2.8

  platforms:
  - name: EL
    versions:
    - 7

  galaxy_tags:
  - centos
  - database
  - influxdb
  - influx
  - rhel
  - timeseries
  - tsdb

dependencies: []
