---
# Hostname/FQDN of InfluxDB server. If using TLS, set this to the domain or
# subdomain associated with the HTTPS certificate.
db_fqdn: example.com

# HTTP settings in the InfluxDB config file. These settings track changes from
# the default config file. The intention is to provide an easier upgrade path
# for integrating changes from newer versions of the config file later.
http:
  enabled: "true"
  bind_address: ":8086"
  auth_enabled: "true"
  https_enabled: "true"
  https_certificate: "/usr/lib/influxdb/tls/{{ db_fqdn }}/fullchain.pem"
  https_private_key: "/usr/lib/influxdb/tls/{{ db_fqdn }}/privkey.pem"
