---
- name: synchronize all CentOS 7 hosts
  hosts: centos7
  become: yes

  pre_tasks:
    - name: import Vault-encrypted variables
      include_vars:
        dir: "{{ inventory_dit }}/vault.yml"

    
  tasks:
    - include_role:
        name: base/centos-7
      tags: 
        - base
        - centos-7
      
    - include_role:
        name: firewalld
      tags: 
        - firewalld
        - centos-7
      
    - include_role:
        name: yum-cron
      tags: 
        - yum-cron
        - centos-7
