---
- name: synchronize all CentOS 7 hosts
  hosts: centos7
  become: yes

  roles:
    - { role: base/centos-7, tags: base }
    - { role: firewalld, tags: firewalld }
    - { role: yum-cron, tags: yum-cron }
