---
- name: synchronize all CentOS 7 hosts
  hosts: centos7
  become: yes

  tasks:
    - include_role:
        name: base/centos-7
      tags:
        - base
        - centos-7

    - include_role:
        name: firewalld
      tags:
        - firewalld
        - centos-7

    - include_role:
        name: yum-cron
      tags:
        - yum-cron
        - centos-7
