---
- name: set up load balancer
  hosts: loadbalancer
  become: yes

  tasks:
    - include_role:
        name: nginx
      tags:
        - nginx
        - loadbalancer

    - include_role:
        name: load-balance
      tags:
        - nginx
        - loadbalancer
