---
- name: Install siege on ansible host
  hosts: ansiHost
  become: yes

  tasks:
    - include_role:
        name: siege-install
      tags:
        - siege
        - siege-install

    - include_role:
        name: siege-run
      tags:
        - siege
        - siege-run
