---
- name: Set up webserver
  hosts: webserver
  become: yes

  tasks:
    - include_role:
        name: nginx
      tags:
        - nginx
        - webserver

    - include_role:
        name: php-fpm
      tags:
        - php-fpm
        - webserver

    - include_role:
        name: california-webserver
      tags:
        - california-webserver
        - webserver
