---
# Coppied from mycourses load-generator.yml example
- name: Configure Siege
  template:
    src: "files/siege.conf"
    dest: "~/.siege/siege.conf"
    seuser: system_u

- name: Push hosts file
  template:
    src: "files/hosts.conf"
    dest: "/usr/local/etc/urls.txt"
    seuser: system_u

- name: Generating Load
  command: "siege"
